### ISSUE TITLE
Two green PRs can merge into a broken main: required checks run against a stale base, and a red main notifies nobody

### ISSUE THREAD

**Issue by vfarcic** [vfarcic/dot-agent-deck#1088]
Two PRs that are each green can merge in sequence and leave `main` broken, because a PR's required checks run against its **merge base** rather than against what `main` becomes once the PRs ahead of it land. The ruleset that protects `main` has `strict = false`, so nothing re-tests a stale branch before it merges.

## Worked example, measured 2026-09-14

`main` was red for ~52 minutes and nobody noticed. Two PRs, both green on their own branches, neither having seen the other:

- **#1066** added a construction site for `dispatch::DispatchContext`.
- **#1081** added a `caller` field to that struct and updated every constructor **that existed on its own base**.

Git merged both cleanly — the conflict is semantic, not textual. The compiler disagreed:

```
error[E0063]: missing field `caller` in initializer of `dispatch::DispatchContext`
```

One compile error took down three of the five required checks at `430dda26`:

| job | step |
| --- | --- |
| `e2e-deterministic` | `cargo test-e2e --retries 1` |
| `build` | `cargo clippy --workspace --all-targets --features e2e,e2e-live -- -D warnings` |
| `build-macos` | `cargo nextest run --workspace` |

(A fourth job, `security`, failed independently in the same run on a real `cargo audit` finding — filed separately.)

**It was repaired by accident.** The only commit touching `src/dispatch.rs` between the red commit and the next green one is `2601bed8`, an unrelated desktop PR (#1076). Its author had to merge `main` in to resolve conflicts, and that merge added the missing field:

```diff
+            // No live caller to report back to — see the sibling tests.
+            caller: None,
```

So a PR that had nothing to do with the break silently fixed it, and five further PRs were merged on top of a red `main` in between.

## Detection already exists — alerting does not

`ci.yml` already runs on `push: branches: [main]`, and its own comment says why: after 2026-07-29, when #269 merged with three build jobs red and `main` was unbuildable for about a day. That comment states the intent as turning "main is broken" from a discovery into **a notification**.

The check fired. It failed. It reported `completed/failure`. **Nothing notified anyone**, so merging continued for another five PRs. The post-merge job is doing its job; the half that tells a human does not exist.

`concurrency: ci-${{ github.ref }}` with `cancel-in-progress: true` compounds it: every push to `main` shares one group, so each merge cancels the previous run. `2601bed8` and `51b7ee9e` never completed a run at all. That is not a correctness hole on its own — `main` is linear, so a later green run vindicates the earlier content — but it means the run list bounces between `failure` and `cancelled` and a red is easy to scroll past.

### 1. Code — must land FIRST

- **Add a `merge_group:` trigger to `ci.yml`.** No workflow in this repository handles `merge_group` today (`grep -rl merge_group .github/workflows/` is empty). A merge queue enabled before this exists would hang every PR forever, waiting for required checks that never run against the queue's branches.
- **Stop cancelling post-merge runs on `main`.** Keep `cancel-in-progress` for pull-request refs, where a superseded run is genuinely waste. Exclude `main` pushes and merge-queue refs so each one completes and can be attributed.
- **Make a red `main` shout.** `scripts/notify.sh` already exists and is the repo's one notification path; a failed post-merge run should use it, or an equivalent. This is the half `ci.yml`'s existing comment promised and never got.

### 2. Repository setting — only AFTER the above

A **merge queue** on the `main-protected` ruleset. It tests each PR against the *projected* `main` with the PRs ahead of it applied, speculatively and in parallel, and merges only what is green. That is exactly the failure above.

`strict = true` ("require branches to be up to date before merging") closes the same hole and is one parameter flip, but it **serialises merging**: every merge invalidates every other open PR, each then needing an update plus a full CI cycle. The 2026-09-14 batch was nine PRs; under `strict` that is nine sequential cycles. Worth knowing as the cheap fallback, not as the recommendation.

## Scope note

The setting half is a repository-admin change and is deliberately **not** part of the code work — the code has to be merged before the setting is safe to enable.

**Comment by vfarcic** [comment]
The code half is in #1090. Two repository-admin follow-ups, both of which must wait for it to merge:

**1. Enable a merge queue on the `main-protected` ruleset.** This is the step the issue already scopes out. `#1090` adds the `merge_group:` trigger that makes it safe: `grep -rl merge_group .github/workflows/` was empty, so the queue would otherwise hang every PR forever on five required contexts that never report against its temporary branches. Current state for reference — `gh api repos/vfarcic/dot-agent-deck/rulesets/20587589` shows `strict_required_status_checks_policy: false` and the five contexts `build`, `build-macos`, `build-windows`, `security`, `e2e-deterministic`, with no merge-queue rule.

**2. Register `TELEGRAM_BOT_TOKEN` and `TELEGRAM_CHAT_ID` as repository secrets.** This one is new information, found while doing the work, and it is not in the issue as written. The issue says "`scripts/notify.sh` already exists and is the repo's one notification path" — true of the script, but the credentials it needs are not on the repository. `gh secret list` returns `ANTHROPIC_API_KEY`, `HOMEBREW_TAP_TOKEN`, `OPENAI_API_KEY`, `RELEASE_TOKEN`, `REVIEW_APP_ID`, `REVIEW_APP_PRIVATE_KEY`, `SCOOP_BUCKET_TOKEN` — neither Telegram variable. They exist only in `.env.vals.yaml`, which is a local `vals` reference file for a developer shell, not a CI source.

So until step 2 happens, `#1090`'s `notify-main-red` job runs, identifies the commit and the failing jobs, writes them to the `::error::` annotation and the step summary — and then skips the send with `notify: TELEGRAM_BOT_TOKEN unset — skipping send`, exiting 0. **The detection half of "make a red `main` shout" lands with #1090; the shouting half needs those two secrets.**

A `GITHUB_TOKEN`-based channel that would have worked with no new secret was considered and rejected: `.github/workflows/issue-labeler.lock.yml` triggers on `issues: opened` and runs `codex exec` with `OPENAI_API_KEY`, so filing an issue per red `main` would spend a real agent credential each time, and the job would have needed a `issues: write` override that contradicts this workflow's own header argument for `persist-credentials: false`. The reasoning is on the PR.

**Comment by vfarcic** [comment]
## Closing: the code half shipped, and the setting half is not available on this repository

### What shipped

PR #1090 (`b753d93e`) delivered all three code items:

- **`merge_group:` trigger** on `ci.yml`, so a queue would not hang every PR on checks that never run.
- **Post-merge runs on `main` are no longer cancelled** — `group: … pull_request && github.ref || github.run_id` with `cancel-in-progress: … == 'pull_request'`, so `main` pushes each get their own group.
- **`notify-main-red`** — the half this issue pointed out `ci.yml`'s own trigger comment had promised since 2026-07-29 and never delivered.

### The setting half cannot be done, and this issue's recommendation was wrong

**"What to change §2" recommends a merge queue on the `main-protected` ruleset. That is not available here.** Measured 2026-09-15, adding the rule via the API — built from the live ruleset so the four existing rules were carried through verbatim:

```
$ gh api -X PUT repos/vfarcic/dot-agent-deck/rulesets/20587589 --input after.json
{"message":"Validation Failed","errors":["Invalid rule 'merge_queue': "],"status":"422"}
```

The rule type is rejected outright. The repository is **public but owned by a User account** (`owner_type: "User"`), which is the likely cause — GitHub's merge-queue documentation states no availability requirements at all, so that is inference from the 422 rather than a documented fact. The option is absent from the ruleset UI for the same reason; nothing was being missed on screen.

The rejected `PUT` changed nothing — the ruleset still carries exactly `deletion, non_fast_forward, pull_request, required_status_checks` with `strict=false`.

**Recording this so the next reader does not retry it.** "Enable the merge queue" is the obvious answer to this class of defect, and this issue currently recommends it.

### What is therefore still true

The original defect is **detected but not prevented**. Two individually-green PRs can still merge into a broken `main`, exactly as #1066 and #1081 did — `strict = false` means required checks still run against a PR's own merge base. What changed is that `notify-main-red` now shouts within one CI cycle instead of the break sitting silent for 52 minutes and being repaired by accident.

### The one remaining lever, and why it was not pulled

`strict_required_status_checks_policy: true` closes the same hole. It was not enabled because the cost here is higher than it first looks: `allow_update_branch` is **false**, so every merge would invalidate every other open PR and each would need a manual update plus a full ~10-minute CI cycle, serialised. On the 2026-09-14 batch of nine PRs that is nine sequential cycles, and the predictable response to that is `--admin`, which converts a gate into ceremony (CLAUDE.md rule 8).

Reopen or file a successor if the calculus changes — for example if this repository moves to an organization, which would make the merge queue available and make this decision moot.
